/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: is the process up and serving requests at all.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: are hard dependencies reachable.
         *
         *     No dependency (Postgres/Redis/vector DB) is consumed by any code
         *     path yet in Phase 0, so readiness currently reduces to liveness.
         *     Phase 1 adds a real Postgres connectivity check here.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Workspaces */
        get: operations["list_my_workspaces_api_v1_workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_v1_workspaces__workspace_id__members_get"];
        put?: never;
        /** Invite Member */
        post: operations["invite_member_api_v1_workspaces__workspace_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members/{target_user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_workspaces__workspace_id__members__target_user_id__delete"];
        options?: never;
        head?: never;
        /** Change Member Role */
        patch: operations["change_member_role_api_v1_workspaces__workspace_id__members__target_user_id__patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents Route */
        get: operations["list_agents_route_api_v1_workspaces__workspace_id__agents_get"];
        put?: never;
        /** Create Agent Route */
        post: operations["create_agent_route_api_v1_workspaces__workspace_id__agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Route */
        get: operations["get_agent_route_api_v1_workspaces__workspace_id__agents__agent_id__get"];
        put?: never;
        post?: never;
        /** Delete Agent Route */
        delete: operations["delete_agent_route_api_v1_workspaces__workspace_id__agents__agent_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/agents/{agent_id}/versions/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Version Route */
        get: operations["get_latest_version_route_api_v1_workspaces__workspace_id__agents__agent_id__versions_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/agents/{agent_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Version Route */
        post: operations["create_version_route_api_v1_workspaces__workspace_id__agents__agent_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/agents/{agent_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Agent Route */
        post: operations["publish_agent_route_api_v1_workspaces__workspace_id__agents__agent_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/agents/{agent_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Run Route */
        post: operations["submit_run_route_api_v1_workspaces__workspace_id__agents__agent_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Bases Route */
        get: operations["list_knowledge_bases_route_api_v1_workspaces__workspace_id__knowledge_bases_get"];
        put?: never;
        /** Create Knowledge Base Route */
        post: operations["create_knowledge_base_route_api_v1_workspaces__workspace_id__knowledge_bases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/knowledge-bases/{knowledge_base_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Base Route */
        get: operations["get_knowledge_base_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__get"];
        put?: never;
        post?: never;
        /** Delete Knowledge Base Route */
        delete: operations["delete_knowledge_base_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/knowledge-bases/{knowledge_base_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents Route */
        get: operations["list_documents_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents_get"];
        put?: never;
        /**
         * Upload Document Route
         * @description 202 — the bytes are durable and ingestion is queued. Chunking and
         *     embedding are background work (Rule 14), so the client polls the
         *     document's `status` rather than waiting on this call.
         */
        post: operations["upload_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/knowledge-bases/{knowledge_base_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Document Route */
        delete: operations["delete_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/knowledge-bases/{knowledge_base_id}/documents/{document_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Document Route */
        post: operations["reindex_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents__document_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/knowledge-bases/{knowledge_base_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Route
         * @description Runs the exact pipeline an agent run uses, so what a user sees here
         *     is what their agent will actually retrieve.
         */
        post: operations["search_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/agents/{agent_id}/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_v1_workspaces__workspace_id__agents__agent_id__runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_api_v1_workspaces__workspace_id__api_keys_get"];
        put?: never;
        /** Issue Api Key */
        post: operations["issue_api_key_api_v1_workspaces__workspace_id__api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/api-keys/{api_key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Key */
        delete: operations["revoke_api_key_api_v1_workspaces__workspace_id__api_keys__api_key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/auth-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Auth Event */
        post: operations["record_auth_event_internal_auth_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/provider-test/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Provider Test */
        post: operations["stream_provider_test_internal_provider_test_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/job-test/enqueue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Echo Job */
        post: operations["enqueue_echo_job_internal_job_test_enqueue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentResponse */
        AgentResponse: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Published Version Id */
            published_version_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AgentVersionResponse */
        AgentVersionResponse: {
            /** Id */
            id: string;
            /** Version Number */
            version_number: number;
            /** Model */
            model: string;
            /** System Instructions */
            system_instructions: string;
            /** Temperature */
            temperature: number | null;
            /** Max Output Tokens */
            max_output_tokens: number | null;
            /** Tools */
            tools: string[];
            /** Knowledge Base Ids */
            knowledge_base_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ApiKeyResponse */
        ApiKeyResponse: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** Body_upload_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents_post */
        Body_upload_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** ChangeMemberRoleRequest */
        ChangeMemberRoleRequest: {
            role: components["schemas"]["Role"];
        };
        /** CitationResponse */
        CitationResponse: {
            /** Chunk Id */
            chunk_id: string;
            /** Kb Document Id */
            kb_document_id: string;
            /** Knowledge Base Id */
            knowledge_base_id: string;
            /** Chunk Index */
            chunk_index: number;
        };
        /** CreateAgentRequest */
        CreateAgentRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Model */
            model: string;
            /** System Instructions */
            system_instructions: string;
            /** Temperature */
            temperature?: number | null;
            /** Max Output Tokens */
            max_output_tokens?: number | null;
            /** Tools */
            tools?: string[];
            /** Knowledge Base Ids */
            knowledge_base_ids?: string[];
        };
        /** CreateAgentResponse */
        CreateAgentResponse: {
            agent: components["schemas"]["AgentResponse"];
            version: components["schemas"]["AgentVersionResponse"];
        };
        /** CreateKnowledgeBaseRequest */
        CreateKnowledgeBaseRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** CreateWorkspaceRequest */
        CreateWorkspaceRequest: {
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** InviteMemberRequest */
        InviteMemberRequest: {
            /** User Id */
            user_id: string;
            /** @default member */
            role: components["schemas"]["Role"];
        };
        /** IssueApiKeyRequest */
        IssueApiKeyRequest: {
            /** Name */
            name: string;
        };
        /** IssuedApiKeyResponse */
        IssuedApiKeyResponse: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Key */
            key: string;
        };
        /** JobTestRequest */
        JobTestRequest: {
            /**
             * Payload
             * @description Arbitrary payload the echo job reports back.
             */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Force Fail
             * @description If true, the echo job always fails — exercises retry/DLQ.
             * @default false
             */
            force_fail: boolean;
            /**
             * Max Attempts
             * @default 3
             */
            max_attempts: number;
        };
        /** JobTestResponse */
        JobTestResponse: {
            /** Job Id */
            job_id: string;
            /** Stream Id */
            stream_id: string;
        };
        /** KbDocumentResponse */
        KbDocumentResponse: {
            /** Id */
            id: string;
            /** Knowledge Base Id */
            knowledge_base_id: string;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** KnowledgeBaseResponse */
        KnowledgeBaseResponse: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Model Version */
            embedding_model_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MemberResponse */
        MemberResponse: {
            /** Workspace Id */
            workspace_id: string;
            /** User Id */
            user_id: string;
            role: components["schemas"]["Role"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProviderTestRequest */
        ProviderTestRequest: {
            /** Prompt */
            prompt: string;
            /** Model */
            model?: string | null;
        };
        /** RecordAuthEventRequest */
        RecordAuthEventRequest: {
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "auth.signup" | "auth.login";
            /** User Id */
            user_id: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "admin" | "member" | "viewer";
        /** RunAgentRequest */
        RunAgentRequest: {
            /** Input */
            input?: {
                [key: string]: unknown;
            };
        };
        /** RunResponse */
        RunResponse: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Status */
            status: string;
            /** Idempotency Key */
            idempotency_key: string | null;
            /** Cost Micro Usd */
            cost_micro_usd: number | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SearchHitResponse */
        SearchHitResponse: {
            /** Chunk Id */
            chunk_id: string;
            /** Kb Document Id */
            kb_document_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Vector Rank */
            vector_rank: number | null;
            /** Keyword Rank */
            keyword_rank: number | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 8
             */
            top_k: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Hits */
            hits: components["schemas"]["SearchHitResponse"][];
            /** Citations */
            citations: components["schemas"]["CitationResponse"][];
            /** Context Text */
            context_text: string;
            /** Used Tokens */
            used_tokens: number;
            /** Budget Tokens */
            budget_tokens: number;
            /** Dropped Chunk Count */
            dropped_chunk_count: number;
        };
        /** UpdateAgentVersionRequest */
        UpdateAgentVersionRequest: {
            /** Model */
            model: string;
            /** System Instructions */
            system_instructions: string;
            /** Temperature */
            temperature?: number | null;
            /** Max Output Tokens */
            max_output_tokens?: number | null;
            /** Tools */
            tools?: string[];
            /** Knowledge Base Ids */
            knowledge_base_ids?: string[];
        };
        /**
         * UploadDocumentResponse
         * @description 202 body. The document is durable and queued; it is not searchable
         *     until ingestion moves it to `indexed`, which the client polls for.
         */
        UploadDocumentResponse: {
            document: components["schemas"]["KbDocumentResponse"];
            /** Job Id */
            job_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            role: components["schemas"]["Role"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_my_workspaces_api_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"][];
                };
            };
        };
    };
    create_workspace_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_workspaces__workspace_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_member_api_v1_workspaces__workspace_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_workspaces__workspace_id__members__target_user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_user_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_member_role_api_v1_workspaces__workspace_id__members__target_user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_user_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeMemberRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_route_api_v1_workspaces__workspace_id__agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_route_api_v1_workspaces__workspace_id__agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_route_api_v1_workspaces__workspace_id__agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_route_api_v1_workspaces__workspace_id__agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_version_route_api_v1_workspaces__workspace_id__agents__agent_id__versions_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_route_api_v1_workspaces__workspace_id__agents__agent_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_agent_route_api_v1_workspaces__workspace_id__agents__agent_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_run_route_api_v1_workspaces__workspace_id__agents__agent_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                agent_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_bases_route_api_v1_workspaces__workspace_id__knowledge_bases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_base_route_api_v1_workspaces__workspace_id__knowledge_bases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKnowledgeBaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_base_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_base_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbDocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_document_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__documents__document_id__reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                document_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_route_api_v1_workspaces__workspace_id__knowledge_bases__knowledge_base_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_v1_workspaces__workspace_id__agents__agent_id__runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
                run_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_workspaces__workspace_id__api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_api_key_api_v1_workspaces__workspace_id__api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedApiKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_v1_workspaces__workspace_id__api_keys__api_key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                api_key_id: string;
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_auth_event_internal_auth_events_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordAuthEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_provider_test_internal_provider_test_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_echo_job_internal_job_test_enqueue_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Internal-Secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
