"""add jwks table for better auth jwt plugin

Revision ID: dcc26fa22f2c
Revises: 9fe576fcc0b7
Create Date: 2026-07-25 16:05:34.293797
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "dcc26fa22f2c"
down_revision: Union[str, None] = "9fe576fcc0b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jwks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("private_key", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jwks")
    # ### end Alembic commands ###
